logging:
  level: debug
  timestamp: true

welcome-message: false

# Web server
web:
  host: '0.0.0.0'
  port: 8080

## Parsers
parsers: []

## Connector modules
connectors:
  vkteams:
    token: "VKT_BOT_TOKEN"
    bot-name: "email_sender_bot"
    base-url: "api.my-company.myteam.mail.ru/bot/v1/"
    repo: https://github.com/mboriskin/connector-vkteams
  slack:
    bot-token: "SLACK_BOT_TOKEN"
    bot-name: "OpsDroid service"
    socket-mode: true
    app-token: "SLACK_APP_TOKEN"
  matrix:
    mxid: "@bot_account_username:matrix.org"
    password: "bot_account_password"
    rooms:
      'main': '#my-corporate-bots:matrix.org'


## Skill modules
skills:
  ## Hello (https://github.com/opsdroid/skill-hello)
  hello: { }  # <- как пример навык по умолчанию

  email_sender:
    path: /opt/opsdroid/skills/email_sender
    no-cache: true
    app-name: my_opsdroid_vkt
